name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust no_std tests
      run: cd packed_struct_nostd_tests && cargo test --verbose
  
  build-cross:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cross
      run: cargo install cross
    - name: Build
      run: cross build --target aarch64-unknown-linux-gnu
    - name: Run tests
      run: cross test --target aarch64-unknown-linux-gnu