[package]
name = "packed_struct_tests"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]
publish = false

[dependencies]
packed_struct = "0.4"
packed_struct_codegen = "0.4"
error-chain = "0.12.0"